### ISSUE TITLE
Tem um token nos primeiro commits

### ISSUE THREAD

**Issue by Ckk3** [Lavrudin/diolinux-team-bot#2]
Nos primeiros commits tem o token da API sem nenhuma proteção, sei que ele ele foi retirado do código e substituído por variaveis de ambiente, esse issue é só pra saber se vcs criaram outro token depois disso pq caso contrário a api fica vulnerável

Parabéns pelo projeto, depois que vi o vídeo me aventurei um pouco nisso de bot e acabei criando um bem simpleszinho kkk, valeu!

**Comment by Lavrudin** [comment]
Oii, @Ckk3.

Todos os tokens que acabaram subindo por acidente foram imediatamente substituídos. De qualquer forma, agradeço muito por se preocupar e nos alertar.

Muito obrigado e fico extremamente feliz por você ter começado a se aventurar no mundo dos bots depois de assistir ao nosso vídeo hahahaa. Vamos evoluir juntos.

Abraços :D

**Comment by Ckk3** [comment]
Tmj mano, tudo de bom pra vocês <3
